name: CI

on: [push]

jobs:
  code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check code style
        run: |
          make code-style

  unused-code:
    name: Check unused code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check code style
        run: |
          make unused-code

  security-issue:
    name: Check security issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check code style
        run: |
          make security-issue

  linter:
    name: Check code linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check code linter
        run: |
          make linter

  type-check:
    name: Run static type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run static type checking
        run: |
          make type-check

  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run test
        run: |
          make test
