name: CI

on: [push]

jobs:
  code-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check code style
        run: |
          make code-style

  import:
    name: Check import
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check import
        run: |
          make import

  unused-code:
    name: Check unused code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check code style
        run: |
          make unused-code

  security-issue:
    name: Check security issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check code style
        run: |
          make security-issue

  security-dependency:
    name: Check security dependency
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check security dependency
        run: |
          make security-dependency

  linter:
    name: Check code linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Check code linter
        run: |
          make linter

  type-check:
    name: Run static type checking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run static type checking
        run: |
          make type-check

  tests:
    name: Run all tests with coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-python
      - name: Run unit tests with coverage
        run: |
          make test-unit-coverage
      - name: Run functional tests with coverage
        run: |
          make test-functional-coverage
